from copy import deepcopy


PROFILE_CONFIGS: dict[str, dict] = {
    "general": {
        "profile": "general",
        "report_title": "合同审查报告",
        "checklist": [
            {
                "key": "parties",
                "title": "合同主体识别",
                "description": "核对甲乙方名称、身份信息和签署主体是否完整。",
                "keywords": ["甲方", "乙方", "当事人", "委托人", "受托人"],
                "red_flags": ["代理人", "授权待补", "另行指定"],
                "missing_severity": "high",
                "risk_severity": "medium",
                "rewrite_hint": "建议在合同首部完整写明各方主体名称、统一社会信用代码和签署代表信息。",
            },
            {
                "key": "scope",
                "title": "标的与服务范围",
                "description": "检查服务内容、交付物或交易标的描述是否明确。",
                "keywords": ["服务内容", "标的", "交付", "产品", "工作内容"],
                "red_flags": ["以甲方要求为准", "不限于", "另行通知"],
                "missing_severity": "high",
                "risk_severity": "medium",
                "rewrite_hint": "建议把标的范围拆成可验收的清单，避免仅以单方通知定义义务。",
            },
            {
                "key": "payment",
                "title": "价款与付款安排",
                "description": "核对金额、付款节点、发票要求和结算条件。",
                "keywords": ["付款", "价款", "金额", "发票", "结算"],
                "red_flags": ["收到回款后支付", "甲方有权延期付款", "不开票"],
                "missing_severity": "high",
                "risk_severity": "high",
                "rewrite_hint": "建议写明固定金额、付款节点、发票类型和逾期付款责任。",
            },
            {
                "key": "acceptance",
                "title": "验收与交付标准",
                "description": "检查验收标准、时限和异议机制。",
                "keywords": ["验收", "交付标准", "成果确认", "异议"],
                "red_flags": ["视为验收", "甲方最终解释", "单方认定"],
                "missing_severity": "medium",
                "risk_severity": "high",
                "rewrite_hint": "建议补充验收时限、书面异议期和客观验收标准。",
            },
            {
                "key": "termination",
                "title": "解除与终止条件",
                "description": "检查解除权触发条件和提前通知机制。",
                "keywords": ["解除", "终止", "提前通知", "单方解除"],
                "red_flags": ["无条件解除", "随时解除", "无需承担责任"],
                "missing_severity": "medium",
                "risk_severity": "high",
                "rewrite_hint": "建议限定解除事由、通知期限和解除后的结算规则。",
            },
            {
                "key": "breach",
                "title": "违约责任",
                "description": "检查违约金、损失赔偿和救济措施。",
                "keywords": ["违约责任", "违约金", "赔偿", "损失"],
                "red_flags": ["不承担任何责任", "最高不超过已付款", "免责"],
                "missing_severity": "high",
                "risk_severity": "high",
                "rewrite_hint": "建议补充违约金或损失赔偿口径，并明确重大违约的救济方式。",
            },
            {
                "key": "dispute",
                "title": "争议解决",
                "description": "检查管辖、仲裁条款和适用法律。",
                "keywords": ["争议解决", "仲裁", "管辖", "人民法院"],
                "red_flags": ["甲方所在地", "乙方所在地", "最终解释权归甲方"],
                "missing_severity": "medium",
                "risk_severity": "medium",
                "rewrite_hint": "建议约定明确且对己方可接受的争议解决机构或法院。",
            },
        ],
    },
    "employment": {
        "profile": "employment",
        "report_title": "劳动合同审查报告",
        "checklist": [
            {
                "key": "term",
                "title": "劳动合同期限",
                "description": "核对试用期、固定期限或无固定期限约定。",
                "keywords": ["合同期限", "试用期", "无固定期限", "劳动合同期限"],
                "red_flags": ["试用期六个月", "另行确定转正时间"],
                "missing_severity": "high",
                "risk_severity": "high",
                "rewrite_hint": "建议明确劳动合同期限、试用期起止和转正条件。",
            },
            {
                "key": "compensation",
                "title": "薪酬与福利",
                "description": "检查工资结构、发薪日期和福利约定。",
                "keywords": ["工资", "薪酬", "奖金", "社保", "公积金"],
                "red_flags": ["视经营情况发放", "不缴纳社保", "绩效另定"],
                "missing_severity": "high",
                "risk_severity": "high",
                "rewrite_hint": "建议明确固定工资、发薪日以及社保公积金缴纳责任。",
            },
            {
                "key": "duties",
                "title": "岗位与工作地点",
                "description": "检查岗位职责和调岗调地点权限。",
                "keywords": ["岗位", "职责", "工作地点", "调岗"],
                "red_flags": ["公司可随时调整", "全国范围调动"],
                "missing_severity": "medium",
                "risk_severity": "medium",
                "rewrite_hint": "建议限定调岗调地点条件，并约定协商程序。",
            },
            {
                "key": "termination",
                "title": "解除与离职安排",
                "description": "检查解除理由、通知期和经济补偿。",
                "keywords": ["解除", "离职", "辞退", "经济补偿"],
                "red_flags": ["无需补偿", "可即时解除", "自动离职"],
                "missing_severity": "high",
                "risk_severity": "high",
                "rewrite_hint": "建议明确解除事由、通知义务和补偿安排。",
            },
        ],
    },
    "lease": {
        "profile": "lease",
        "report_title": "租赁合同审查报告",
        "checklist": [
            {
                "key": "subject",
                "title": "租赁标的与交付状态",
                "description": "核对房屋或设备信息、交付条件和附属清单。",
                "keywords": ["租赁物", "房屋", "面积", "交付"],
                "red_flags": ["以现状为准", "面积误差不调整"],
                "missing_severity": "high",
                "risk_severity": "medium",
                "rewrite_hint": "建议补充地址、面积、附属设施和交付状态清单。",
            },
            {
                "key": "rent",
                "title": "租金与押金",
                "description": "检查租金、押金、调整规则和返还条件。",
                "keywords": ["租金", "押金", "保证金", "递增"],
                "red_flags": ["单方调整租金", "押金不退", "违约即没收押金"],
                "missing_severity": "high",
                "risk_severity": "high",
                "rewrite_hint": "建议明确租金周期、调整条件和押金返还时间。",
            },
            {
                "key": "repair",
                "title": "维修责任",
                "description": "检查大修、小修和费用承担。",
                "keywords": ["维修", "维护", "保养", "修缮"],
                "red_flags": ["全部由承租人承担", "出租人不负责维修"],
                "missing_severity": "medium",
                "risk_severity": "medium",
                "rewrite_hint": "建议区分结构性维修与日常维护责任。",
            },
            {
                "key": "termination",
                "title": "提前解约与腾退",
                "description": "检查提前解约、违约腾退和恢复原状安排。",
                "keywords": ["提前解约", "腾退", "恢复原状", "解除"],
                "red_flags": ["出租人可随时收回", "装修无偿归属"],
                "missing_severity": "medium",
                "risk_severity": "high",
                "rewrite_hint": "建议明确提前解约条件、违约责任和腾退结算规则。",
            },
        ],
    },
    "nda": {
        "profile": "nda",
        "report_title": "保密协议审查报告",
        "checklist": [
            {
                "key": "confidential_scope",
                "title": "保密信息范围",
                "description": "核对保密信息定义、例外情形和载体。",
                "keywords": ["保密信息", "秘密信息", "商业秘密", "例外"],
                "red_flags": ["全部信息均保密", "无任何例外"],
                "missing_severity": "high",
                "risk_severity": "medium",
                "rewrite_hint": "建议明确保密信息定义，并写入公开信息等合理例外。",
            },
            {
                "key": "use_limit",
                "title": "使用限制与披露范围",
                "description": "检查信息使用目的、内部知悉范围和第三方披露要求。",
                "keywords": ["使用", "披露", "知悉范围", "第三方"],
                "red_flags": ["可用于其他目的", "关联方不限"],
                "missing_severity": "medium",
                "risk_severity": "high",
                "rewrite_hint": "建议限定使用目的，并要求第三方承担同等保密义务。",
            },
            {
                "key": "term",
                "title": "保密期限",
                "description": "检查协议期限与保密义务存续期。",
                "keywords": ["保密期限", "有效期", "存续"],
                "red_flags": ["永久保密", "期限另定"],
                "missing_severity": "medium",
                "risk_severity": "low",
                "rewrite_hint": "建议明确协议期限和义务存续期间。",
            },
            {
                "key": "breach",
                "title": "泄密责任",
                "description": "检查泄密责任、损害赔偿和禁令救济。",
                "keywords": ["违约责任", "泄密", "赔偿", "禁令"],
                "red_flags": ["不承担间接损失", "责任上限极低"],
                "missing_severity": "high",
                "risk_severity": "medium",
                "rewrite_hint": "建议补充泄密损失赔偿及紧急救济条款。",
            },
        ],
    },
    "sales": {
        "profile": "sales",
        "report_title": "买卖合同审查报告",
        "checklist": [
            {
                "key": "goods",
                "title": "货物规格与数量",
                "description": "检查规格型号、数量、质量标准和附件清单。",
                "keywords": ["规格", "型号", "数量", "质量标准"],
                "red_flags": ["以实际发货为准", "规格可调整"],
                "missing_severity": "high",
                "risk_severity": "medium",
                "rewrite_hint": "建议通过附件列明货物规格、数量和质量标准。",
            },
            {
                "key": "delivery",
                "title": "交货与风险转移",
                "description": "检查交货地点、时间、运输和风险转移点。",
                "keywords": ["交货", "交付", "运输", "风险转移"],
                "red_flags": ["发货即视为交付", "风险由买方承担"],
                "missing_severity": "high",
                "risk_severity": "high",
                "rewrite_hint": "建议明确交货地点、签收规则和风险转移节点。",
            },
            {
                "key": "payment",
                "title": "价款结算",
                "description": "检查付款节点、结算周期和发票义务。",
                "keywords": ["付款", "结算", "发票", "尾款"],
                "red_flags": ["验收后另议", "付款时间不确定"],
                "missing_severity": "high",
                "risk_severity": "high",
                "rewrite_hint": "建议明确预付款、尾款、发票和逾期付款责任。",
            },
            {
                "key": "warranty",
                "title": "质量保证与售后",
                "description": "检查质保期、瑕疵处理和退换货。",
                "keywords": ["质保", "售后", "退换货", "维修"],
                "red_flags": ["概不退换", "仅按厂商政策"],
                "missing_severity": "medium",
                "risk_severity": "medium",
                "rewrite_hint": "建议补充质保期、维修响应和退换货流程。",
            },
        ],
    },
}


def get_profile_config(profile: str) -> dict:
    normalized = (profile or "general").strip().lower()
    config = PROFILE_CONFIGS.get(normalized, PROFILE_CONFIGS["general"])
    return deepcopy(config)
